test: Add test for auto create account
godwokenrises/godwoken-tests pull request #145
Opened 2022-07-08 15:19 UTC by classicalliu

2022-07-12 10:57 UTC, zeroqn commented on contracts/test/autoCreateAccount.js
> +// import { ERC20_HEX, ERC20_HEX_ABI } from "../scripts/erc20_hex";
Remove these code?

2022-07-12 10:57 UTC, zeroqn approved these changes

2022-07-12 12:42 UTC, ShookLyngs requested changes

2022-07-12 12:42 UTC, ShookLyngs commented on contracts/test/autoCreateAccount.js
> +    throw new Error("");
Maybe give the error a clear message?

2022-07-13 03:39 UTC, classicalliu commented on contracts/test/autoCreateAccount.js
> +// import { ERC20_HEX, ERC20_HEX_ABI } from "../scripts/erc20_hex";
Ohh, sorry, removed

2022-07-13 03:40 UTC, classicalliu commented on contracts/test/autoCreateAccount.js
> +    throw new Error("");
Updated

2022-07-13 06:03 UTC, ShookLyngs commented on contracts/test/autoCreateAccount.js
> +    throw new Error("");
Did you forget to push the commit?

2022-07-14 02:43 UTC, classicalliu commented on contracts/test/autoCreateAccount.js
> +    throw new Error("");
> Did you forget to push the commit?

Pushed to wrong branch ... sorry ..

2022-07-14 03:44 UTC, zeroqn approved these changes

2022-07-14 06:10 UTC, ShookLyngs approved these changes

2022-07-14 06:10 UTC, merged