Test: Add contract upgrade test
godwokenrises/godwoken-tests pull request #207
Opened 2022-11-24 09:13 UTC by Dawn-githup

2022-12-07 11:36 UTC, Flouse commented
Re-running test:
- https://github.com/godwokenrises/godwoken-tests/actions/runs/3620068240/jobs/6140692170

2022-12-07 11:36 UTC, Flouse requested changes

2022-12-07 11:36 UTC, Flouse commented on contracts/test/UpgradeContract.js
> +    it("Deploy and call recursive functions", async () => {
Please rename the test

2022-12-07 11:36 UTC, Flouse commented on contracts/contracts/ERC721MSHKUUPSTokenUpgrade.sol
> +    }
please format the code by the way.

2022-12-08 03:29 UTC, Dawn-githup commented on contracts/test/UpgradeContract.js
> +    it("Deploy and call recursive functions", async () => {
modified

2022-12-08 03:30 UTC, Dawn-githup commented
> Re-running test:
> 
> * https://github.com/godwokenrises/godwoken-tests/actions/runs/3620068240/jobs/6140692170

This problem has been resolved

2022-12-08 04:21 UTC, Flouse approved these changes

2022-12-08 04:21 UTC, merged