feat: add gasless test
godwokenrises/godwoken-tests pull request #213
Opened 2022-12-20 02:54 UTC by magicalne

Run gasless test on hardhat and gw_alphanet_v1 from https://github.com/godwokenrises/account-abstraction/tree/gw-gasless.

2022-12-20 03:21 UTC, RetricSu approved these changes

2022-12-27 03:12 UTC, Flouse approved these changes

2023-01-10 12:43 UTC, Flouse requested changes

2023-01-10 12:43 UTC, Flouse commented on .github/workflows/gasless-test.yml
> +        yarn run hardhat test --network gw_alphanet_v1
@magicalne Could you add the test cmd for gw_testnet_v1?

2023-01-10 23:19 UTC, Pumpitza approved these changes

2023-01-11 02:21 UTC, magicalne commented on .github/workflows/gasless-test.yml
> +        yarn run hardhat test --network gw_alphanet_v1
OK

2023-01-11 02:25 UTC, magicalne commented on .github/workflows/gasless-test.yml
> +        yarn run hardhat test --network gw_alphanet_v1
Done

2023-01-11 12:13 UTC, Flouse approved these changes

2023-01-11 12:13 UTC, merged