Add Calc test
godwokenrises/godwoken-tests pull request #76
Opened 2022-03-14 11:47 UTC by Dawn-githap

pull Calc testing!

2022-03-14 16:38 UTC, Flouse commented
Please format the code style.

2022-03-15 01:57 UTC, Dawn-githap commented
format the Calc test

2022-03-15 05:01 UTC, keroro520 reviewed
The `contracts/package-lock.json` update so many lines. What happens to package-lock.json?

2022-03-15 05:26 UTC, Flouse requested changes

2022-03-15 05:26 UTC, Flouse commented on contracts/test/Calc.js
> +      const sumBalance = await hardhatCalc.sub(5,6);
Please use the `expect` function to check the result.

2022-03-15 05:26 UTC, Flouse commented on contracts/test/Calc.js
> +  });
Add new line at the end of file

2022-03-15 10:16 UTC, Dawn-githap commented
> `contracts/package-lock.json`更新这么多行。package-lock.json 会发生什么？
'contracts/package-lock.json' changes do not need to update dependencies. I will delete this lock

2022-03-15 10:54 UTC, closed without merging